// The Conquest update (the owner's ask: win the game by owning the whole map, by conquest or alliance). The world is
// a map of provinces of its own, generated by how many realms share it (2 to 12: the town and its rivals, chosen on
// the New Town screen), each province a country of one of the ten lands with a settlement, a fort, what it yields to
// whoever holds it and now and then a landmark. Nothing here touches the raids, trips and quests the game has: the
// conquest is beside them. The generator is sim/conquest/world.ts; the campaign (armies, squads, battles) comes in
// its own steps. Numbers are starting points for tuning.

import type { Biome } from './biomes';
import type { Material } from './materials';

export const REALMS_MIN = 2;
export const REALMS_MAX = 12;
/** The realms a new town shares the world with when nothing is chosen: the town and the four powers of old. */
export const REALMS_DEFAULT = 5;
/** Provinces for every realm in the world (the realms start with `START_PROVINCES` each; the rest are free). */
export const PROVINCES_PER_REALM = 6;
export const START_PROVINCES = 2;
/** The world's side in cells, by the realms in it (a 2-realm world 50 cells across, a 12-realm world 120). */
export const worldSide = (realms: number) => 36 + 7 * Math.max(REALMS_MIN, Math.min(REALMS_MAX, realms));
/** The share of the world that is dry land, about. */
export const LAND_SHARE = 0.62;

/** What a cell of the world is: the sea, impassable mountain, or one of the ten lands. */
export type WorldCell = 'water' | 'mountain' | Biome;
export const CELL_CODES: readonly WorldCell[] = ['water', 'mountain', 'forest', 'desert', 'tundra', 'coast', 'swamp', 'jungle', 'highlands', 'ashlands', 'steppe', 'taiga'];
export const CELL_CODE: Readonly<Record<WorldCell, number>> = Object.fromEntries(CELL_CODES.map((c, i) => [c, i])) as Record<WorldCell, number>;

/** Settlements, smallest first: what each gives its holder a day in coins and recruits. */
export interface SettlementTier {
  id: 'hamlet' | 'village' | 'town' | 'city' | 'capital';
  name: string;
  coins: number;
  recruits: number;
  /** The province's yield of its material a day, multiplied. */
  yieldMult: number;
}
export const TIERS: readonly SettlementTier[] = [
  { id: 'hamlet', name: 'Hamlet', coins: 2, recruits: 0.5, yieldMult: 1 },
  { id: 'village', name: 'Village', coins: 5, recruits: 1, yieldMult: 1.5 },
  { id: 'town', name: 'Town', coins: 10, recruits: 2, yieldMult: 2 },
  { id: 'city', name: 'City', coins: 18, recruits: 3, yieldMult: 3 },
  { id: 'capital', name: 'Capital', coins: 30, recruits: 4, yieldMult: 4 },
];

/** Forts, none to the strongest: a battle for the province starts the holder on its walls. */
export const FORTS: readonly { id: 'none' | 'palisade' | 'keep' | 'citadel'; name: string; walls: number }[] = [
  { id: 'none', name: 'No walls', walls: 0 },
  { id: 'palisade', name: 'Palisade', walls: 1 },
  { id: 'keep', name: 'Stone keep', walls: 2 },
  { id: 'citadel', name: 'Citadel', walls: 3 },
];

/** What each land yields to its holder (the material, and how much a day at a hamlet). */
export const YIELD_BY_LAND: Readonly<Record<Biome, { material: Material; amount: number }>> = {
  forest: { material: 'wood', amount: 3 },
  desert: { material: 'gold', amount: 0.5 },
  tundra: { material: 'bone', amount: 2 },
  coast: { material: 'fish', amount: 3 },
  swamp: { material: 'herbs', amount: 2 },
  jungle: { material: 'fruit', amount: 3 },
  highlands: { material: 'iron_ore', amount: 2 },
  ashlands: { material: 'sulphur', amount: 1.5 },
  steppe: { material: 'hide', amount: 2 },
  taiga: { material: 'wood', amount: 2.5 },
};

/** A province's landmark: something besides its settlement that colours it. */
export type LandmarkKind = 'shrine' | 'mine' | 'ruins' | 'lair' | 'crossroads' | 'harbour';
export const LANDMARKS: Readonly<Record<LandmarkKind, { name: string; text: string }>> = {
  shrine: { name: 'Shrine', text: 'A holy place: the gods look kindly on its holder.' },
  mine: { name: 'Mine', text: 'Old diggings still rich in ore: more of the land\'s yield.' },
  ruins: { name: 'Ruins', text: 'A fallen city: coins and relics for those who dig.' },
  lair: { name: 'Lair', text: 'Something dangerous dens here: a province that must be cleared before it is held.' },
  crossroads: { name: 'Crossroads', text: 'Roads meet: armies march through it quickly, and trade pays.' },
  harbour: { name: 'Harbour', text: 'A sheltered anchorage: the way to the provinces across the water.' },
};
/** How likely a province is to have a landmark, and the odds of each kind where one lies. */
export const LANDMARK_CHANCE = 0.35;
export const LANDMARK_ODDS: Readonly<Record<LandmarkKind, number>> = { shrine: 2, mine: 3, ruins: 2, lair: 3, crossroads: 2, harbour: 0 };

/** Province names: a first part by the land, a second by what's there. */
export const NAME_FIRST: Readonly<Record<Biome, readonly string[]>> = {
  forest: ['Oak', 'Elm', 'Green', 'Thorn', 'Hollow', 'Fern', 'Alder', 'Birch', 'Deep', 'Wyld'],
  desert: ['Sun', 'Dust', 'Red', 'Salt', 'Scorch', 'Dune', 'Amber', 'Glass', 'Bone', 'Mirage'],
  tundra: ['Frost', 'Rime', 'Snow', 'Pale', 'Ice', 'Grey', 'Hoar', 'Winter', 'Bleak', 'Skald'],
  coast: ['Salt', 'Gull', 'Tide', 'Wave', 'Reef', 'Shell', 'Foam', 'Harbour', 'Cliff', 'Seal'],
  swamp: ['Fen', 'Mire', 'Bog', 'Reed', 'Black', 'Moss', 'Marsh', 'Sedge', 'Dank', 'Eel'],
  jungle: ['Vine', 'Rain', 'Emerald', 'Orchid', 'Canopy', 'Serpent', 'Monsoon', 'Ape', 'Tangle', 'Fever'],
  highlands: ['Crag', 'Stone', 'High', 'Cold', 'Eagle', 'Iron', 'Scree', 'Storm', 'Tor', 'Fell'],
  ashlands: ['Ash', 'Cinder', 'Ember', 'Slag', 'Smoke', 'Char', 'Soot', 'Brim', 'Scoria', 'Dread'],
  steppe: ['Horse', 'Wind', 'Wide', 'Grass', 'Khan', 'Open', 'Long', 'Dry', 'Falcon', 'Bannock'],
  taiga: ['Pine', 'Wolf', 'Spruce', 'Bear', 'Larch', 'Cold', 'Needle', 'Dark', 'Lantern', 'Elk'],
};
export const NAME_SECOND: readonly string[] = ['ford', 'march', 'hold', 'reach', 'vale', 'mere', 'wick', 'stead', 'moor', 'gate', 'bridge', 'haven', 'ridge', 'field', 'wold', 'dale', 'cross', 'watch', 'barrow', 'fall'];
