// Generated by tools/compose-sheets.cjs from the Craftpix packs (see CREDITS.md): do not edit by hand.

// (the sheets are files beside the page, copied there by build.mjs and build-web.mjs, not inlined into the script)
import manifest from './packs.json';

export const packUrl = (id: string) => `packs/${id}.png`;
export const PACK_LAYOUT = manifest as Record<string, { w: number; h: number; perRow: number; rows: string[]; counts: Record<string, number>; figure: number; facesRight: boolean }>;
